package com.spring.model;
// Generated May 11, 2017 4:38:35 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rating generated by hbm2java
 */
@Entity
@Table(name = "rating", catalog = "clothesshop_v5")
public class Rating implements java.io.Serializable {

	private Integer id;
	private Integer productId;
	private Integer rating;

	public Rating() {
	}

	public Rating(Integer productId, Integer rating) {
		this.productId = productId;
		this.rating = rating;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ProductId")
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "Rating")
	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

}
